services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: deep_analysis
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build:
      context: .
      dockerfile: TestovoeDeepAnalysis/Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: